### ISSUE TITLE
Delete Item(s) on Wishlist

### ISSUE THREAD

**Issue by psujit3** [CSCI-GA-2820-SP23-001/wishlists#11]
**As a** customer
**I need** to be able to delete items from my wishlist
**So that** I can keep track of my changing wants and needs while shopping online
   
 ### Details and Assumptions
 * Customers can delete only one item at a time from their wishlist
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the service is running
 When I delete an item from my wishlist
 Then that item should disappear from the wishlist and be removed from the database
```

**Comment by aafiyajamal** [comment]
03/07 - Submitted initial pull request, but realized that my code was missing code from test_routes.py, so need to go back and incorporate

**Comment by aafiyajamal** [comment]
03/20 - Test is dependent on creation of read request
