### ISSUE TITLE
Create Kubernetes Cluster on IBM

### ISSUE THREAD

**Issue by taliareg** [CSCI-GA-2820-SP23-001/wishlists#47]
**As a** developer
**I need** an Kubernetes Cluster
**So that** we can deploy to the cloud
   
 ### Details and Assumptions
 *first step of cloud deployment
*everyone on the team needs an IBM account
*Neal will need to add in the other individuals to his account, we need instructions from Prof Rofrano
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given we have made a cluster
 When we try to deploy to the IBM cloud
 Then we can access our cluster
```

**Comment by johnbennion** [comment]
Re-using the container that Neal created for the lab last week. Can confirm that I am able to log in and access it.

**Comment by johnbennion** [comment]
Namespace is nyu-wishlists
