### ISSUE TITLE
Add Dev/Prod namespace in Kubernetes

### ISSUE THREAD

**Issue by taliareg** [CSCI-GA-2820-SP23-001/wishlists#49]
**As a** developer
**I need** separate Kubernetes namespaces
**So that** I can deploy both product and development versions of the service
   
 ### Details and Assumptions
 * Dev port is 31001 and prod port is 31002
 * note this is for the K8s namespace not the cloud namespace

 ### Acceptance Criteria  
   
 ```gherkin
 Given we are logged on to IBM cloud
 When we have namespaces
 Then we should have one for product and one for development
```

**Comment by johnbennion** [comment]
Important to make sure the dev port is 31001 and the prod port is 31002

**Comment by johnbennion** [comment]
Stuck in creating the build to the IBM server, something is going on and have put in a ticket in "troubleshooting" on Slack.

**Comment by johnbennion** [comment]
Created a separate issue to track progress and will continue this in Sprint 3
